apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sagarmendiratta410/argocd-app-config.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
